/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ballotSol from "./Ballot.sol";
export type { ballotSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { Ballot } from "./Ballot.sol/Ballot";
export { Ballot__factory } from "./factories/Ballot.sol/Ballot__factory";
export type { MyContract } from "./Ballot.sol/MyContract";
export { MyContract__factory } from "./factories/Ballot.sol/MyContract__factory";
export { Lock__factory } from "./factories/Lock__factory";
