import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./_components/Sidebar";
import { Toaster } from "react-hot-toast";

const font = Inter({
  display: "swap",
});

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <div className="grid grid-cols-[300px_max-content]">
          <Sidebar />
          <div className="border-l border-l-gray-200 min-h-screen p-4">
            {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
